import { createSlice } from '@reduxjs/toolkit'

const initialState = {
    role: null
}

/* This code is creating a Redux slice using the `createSlice` function from the `@reduxjs/toolkit`
library. The slice is named "profile" and has an initial state with a `role` property set to `null`.
It also has a single reducer function called `setRole` that takes in a `state` object and an
`action` object, and sets the `role` property of the `state` object to the `role` value in the
`action` payload. The `createSlice` function automatically generates action creators and action
types for the `setRole` reducer. Finally, the code exports the `setRole` action creator, a selector
function `getRole` that returns the `role` property from the state, and the reducer function
generated by `createSlice`. */
const profileSlice = createSlice({
  name: 'profile',
  initialState,
  reducers: {
    setRole: (state, action) => {
        state.role = action.payload.role
    },
  }
});

export const { setRole } = profileSlice.actions

export const getRole = state => state.profile.role

export default profileSlice.reducer